# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    gulp build --ship
    gulp bundle --ship
    gulp package-solution --ship
    dir
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/shareoint/solution'
    Contents: 'myquotes-webpart.sppkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: 'My install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'

